# Generated by Django 4.1.3 on 2023-06-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
